// <auto-generated />
namespace Asana.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Deadline_ForProject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deadline_ForProject));
        
        string IMigrationMetadata.Id
        {
            get { return "201809292353488_Deadline_ForProject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
