// <auto-generated />
namespace Asana.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DescriptionProperty_IsAdded_InChatRoom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DescriptionProperty_IsAdded_InChatRoom));
        
        string IMigrationMetadata.Id
        {
            get { return "201809041250306_DescriptionProperty_IsAdded_InChatRoom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
