// <auto-generated />
namespace Asana.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MaxStringLength_For_Title_IsChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MaxStringLength_For_Title_IsChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201810010844232_MaxStringLength_For_Title_IsChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
