// <auto-generated />
namespace Asana.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class VirtualTaskProperty_IsAdded_ToTaskLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VirtualTaskProperty_IsAdded_ToTaskLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201810091249439_VirtualTaskProperty_IsAdded_ToTaskLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
