// <auto-generated />
namespace Asana.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreationDate_Removed_TaskLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreationDate_Removed_TaskLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201810121638191_CreationDate_Removed_TaskLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
